# Generated by Django 4.0.2 on 2022-02-19 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_employee_user_alter_employer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='display_picture',
            field=models.URLField(default='https://api.workanetworks.com/static/media/display-picture/9/download.png'),
        ),
        migrations.AlterField(
            model_name='employer',
            name='company_logo',
            field=models.URLField(default='https://api.workanetworks.com/static/media/company-logo/krp5oktnm2/306424.png'),
        ),
    ]
