# Generated by Django 4.0.2 on 2022-02-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_employee_display_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
    ]
