# Generated by Django 4.0.2 on 2022-03-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_plans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Plans',
        ),
    ]
