# Generated by Django 4.0.2 on 2022-03-17 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='plan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='registered_plan', to='api.plans'),
            preserve_default=False,
        ),
    ]
