# Generated by Django 4.0.2 on 2022-03-17 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_employer_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='employer',
            name='plan_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='employer',
            name='plan',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_plan', to='api.plans'),
        ),
    ]
