# Generated by Django 4.0.2 on 2022-03-17 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_employer_plan_active_alter_employer_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanUpgradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transanction', models.CharField(max_length=225)),
                ('status', models.CharField(choices=[['pending', 'pending'], ['reject', 'reject'], ['confirmed', 'confirmed']], default='pending', max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upgrade_record', to='api.plans')),
            ],
        ),
    ]
