# Generated by Django 4.0.2 on 2022-03-17 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_planupgraderecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='registered_plan', to='api.plans'),
        ),
    ]
