# Generated by Django 4.0.2 on 2022-04-08 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_alter_employer_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobspost',
            name='shortlist_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
