# Generated by Django 4.0.2 on 2022-04-20 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_alter_applyjob_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('employee', 'employee'), ('employer', 'employer'), ('staff', 'staff'), ('administrator', 'administrator')], max_length=13),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('other_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[['male', 'male'], ['female', 'female']], max_length=6)),
                ('phone', models.CharField(max_length=255)),
                ('location', models.CharField(default='', max_length=255)),
                ('about', models.TextField(default='')),
                ('display_picture', models.URLField(default='https://api.workanetworks.com/media/display-picture/7/download.png')),
                ('uid', models.CharField(max_length=12, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
