# Generated by Django 4.0.2 on 2022-04-20 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_alter_user_account_type_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='other_name',
        ),
    ]
