# Generated by Django 4.0.2 on 2022-04-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_paymenttrackrecord_narration'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cv',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
