# Generated by Django 4.0.2 on 2022-04-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_employee_cv_employee_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='read',
            field=models.BooleanField(default=False, max_length=255),
        ),
        migrations.AddField(
            model_name='support',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
    ]
