# Generated by Django 4.0.2 on 2022-05-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_support_read_support_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='roles',
            field=models.TextField(default='employer,applicant,interview,employement,payroll'),
            preserve_default=False,
        ),
    ]
