# Generated by Django 4.0.2 on 2022-05-12 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staff_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='applyjob',
            name='note',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='applyjob',
            name='status',
            field=models.CharField(choices=[['processing', 'processing'], ['accept', 'accepted'], ['shortlist', 'shortlisted'], ['decline', 'declined'], ['suspend', 'suspend']], default='processing', max_length=255),
        ),
    ]
