# Generated by Django 4.0.2 on 2022-02-20 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0004_employmentrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviews',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
