# Generated by Django 4.0.2 on 2022-04-08 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_interviews_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employmentrequest',
            name='interview',
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='mode',
            field=models.CharField(choices=[['direct', 'direct'], ['interview', 'interview']], default='interview', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employmentrequest',
            name='mode_key',
            field=models.CharField(default='jjjjjj', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviews',
            name='questioned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='objectiveinterviewanswers',
            name='status',
            field=models.CharField(default='orrect', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='objectiveinterviewquestions',
            name='answer',
            field=models.CharField(default='a', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theoryinterviewanswers',
            name='status',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AlterField(
            model_name='employmentrequest',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
