# Generated by Django 4.0.2 on 2022-05-07 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_interviews_refusal_date_interviews_refusal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='employmentrequest',
            name='status',
            field=models.CharField(choices=[['pending', 'pending'], ['processed', 'processed']], default='pending', max_length=200),
        ),
    ]
