# Generated by Django 4.0.2 on 2022-05-07 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_employmentrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentrequest',
            name='status',
            field=models.CharField(choices=[['pending', 'pending'], ['processed', 'processed'], ['suspended', 'suspended']], default='pending', max_length=200),
        ),
    ]
