# Generated by Django 4.0.2 on 2022-05-07 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staff_roles'),
        ('interview', '0009_alter_employmentrequest_status'),
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='company_email',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='employer_email',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='employer_uid',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='job_title',
        ),
        migrations.AddField(
            model_name='employment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.employer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employment',
            name='req',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='interview.employmentrequest'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employment',
            name='job_key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobspost'),
        ),
    ]
