# Generated by Django 4.0.2 on 2022-05-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_employment_company_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employment',
            name='company',
        ),
    ]
