# Generated by Django 4.0.2 on 2022-05-07 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_remove_employment_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employment',
            old_name='job_key',
            new_name='job',
        ),
    ]
