# Generated by Django 4.0.2 on 2022-05-07 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_alter_employmentrequest_status'),
        ('api', '0053_staff_roles'),
        ('administrator', '0004_rename_job_key_employment_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employment',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employed_job', to='api.jobspost'),
        ),
        migrations.AlterField(
            model_name='employment',
            name='req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_employment', to='interview.employmentrequest'),
        ),
    ]
