# Generated by Django 4.0.2 on 2022-05-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_employment_job_alter_employment_req'),
    ]

    operations = [
        migrations.AddField(
            model_name='employment',
            name='status',
            field=models.CharField(default='active', max_length=255),
            preserve_default=False,
        ),
    ]
