# Generated by Django 4.0.2 on 2022-05-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_employment_currency_alter_employment_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='payment_key',
            field=models.CharField(default='1234567890', max_length=16),
            preserve_default=False,
        ),
    ]
