# Generated by Django 4.0.2 on 2022-05-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_payroll_monthly_charge_alter_payroll_job_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='balance',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
