# Generated by Django 4.0.2 on 2022-05-10 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_payroll_employee_alter_payroll_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payroll',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
