# Generated by Django 4.0.2 on 2022-05-10 19:13

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staff_roles'),
        ('administrator', '0012_payroll_created_payroll_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('balance', models.PositiveIntegerField()),
                ('transaction', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='api.staff')),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_history', to='administrator.payroll')),
            ],
        ),
    ]
