# Generated by Django 4.0.2 on 2022-05-11 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0053_staff_roles'),
        ('administrator', '0013_payrollhistory'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employment',
            unique_together={('job', 'employees_email')},
        ),
    ]
