# Generated by Django 4.0.2 on 2022-05-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_userlogs_joblogs_adminlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='log',
            field=models.CharField(choices=[['post', 'post'], ['request', 'support'], ['support', 'support'], ['delete', 'delete'], ['upgrade', 'upgrade'], ['payment', 'payment']], max_length=200),
        ),
        migrations.AlterField(
            model_name='joblogs',
            name='log',
            field=models.CharField(choices=[['post', 'post'], ['interview', 'interview'], ['shortlist', 'shortlist'], ['close', 'close'], ['update', 'update']], max_length=200),
        ),
    ]
