# Generated by Django 4.0.2 on 2022-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_alter_adminlog_log_alter_joblogs_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminlog',
            name='log',
            field=models.CharField(choices=[['post', 'post'], ['request', 'support'], ['support', 'support'], ['delete', 'delete'], ['upgrade', 'upgrade'], ['payment', 'payment'], ['joined', 'joined']], max_length=200),
        ),
    ]
