from django.urls import path

from administrator import views

app_name = 'administrator'
urlpatterns = [
    path('employee/list/', views.employee_list_card, name='employee_list'),
    path('employer/list/', views.employer_list_card, name='employer_list'),
    path('jobs/list/<status>', views.job_listing, name='jobs_list'),
    path('jobs/list/', views.job_listing, name='jobs_list'),
    path('employee/<str:pid>/', views.employee_details, name='employee_details'),
    path('employer/<str:pid>/', views.employer_details, name='employer_details'),
    path('job/<str:job_key>/', views.job_details, name='job_details'),
    path('job/applications/<str:job_key>/', views.job_applications, name='job_applications'),
    path('interviews/', views.interview_list, name='interviews'),
    path('interview/submitted/<str:uid>', views.interview_submissions, name='interview_submitted'),
    path('interview/preview/answers/<str:iid>/<str:uid>', views.view_employee_interview_answer,
         name='interview_answers'),
    path('interview/preview/question/<str:iid>/', views.interview_questions, name='interview_question'),
    path('dm/chat/', views.admin_chat, name='admin_dm_chat'),
    path('staff/register', views.add_staff, name='add_staff'),
    path('super/staff/register', views.add_super_staff, name='add_super_staff'),
    path('staff/login', views.staff_login, name='staff_login'),
    path('staff/logout', views.staff_logout, name='staff_logout'),
    path('', views.index, name='index'),
    path('req_login/', views.req_login, name='req_login'),
    path('download_pdf/', views.download_pdf, name='download_pdf'),
    path('preview/cv/<str:pid>', views.preview_cv, name='preview_cv'),
    path('support_messages/', views.support_messages, name='support_messages'),
    path('support_messages/<str:mid>', views.read_support_messages, name='read_support_messages'),
    path('employment_form/', views.employment_form, name='employment_form'),
    path('employment_requests/', views.employment_requests, name='employment_requests'),
    path('process_employment/<str:req_id>', views.process_employment, name='process_employment'),
    path('process_payroll/<str:req_id>', views.process_payroll, name='process_payroll'),
    path('employments/', views.employments, name='employments'),
    path('payrolls/', views.payroll_list, name='payrolls'),
    path('create_payroll/<str:job_id>/<str:uid>', views.create_payroll, name='create_payroll'),
    path('payroll/payment/<str:pay_id>', views.make_payroll_payment, name='make_payroll_payment'),
    path('payroll/history/<str:pay_id>', views.payroll_payments, name='payroll_payments'),
    path('staffs', views.staff_list, name='staff_list'),
    path('access_denied', views.access_denied, name='access_denied'),
    path('staff/<str:uid>', views.update_staff, name='update_staff'),
    path('toggle/support_messages/<str:mid>', views.toggle_support_message, name='toggle_support_message'),
    path('report', views.report, name='report'),
    path('report/print/<str:start_date>/<str:end_date>', views.print_report, name='print_report'),
    path('decline_job/<job_id>', views.decline_job, name='decline_job'),
    path('approve_job/<job_id>', views.approve_job, name='approve_job'),
    path('suspend_application/<aid>', views.suspend_application, name='suspend_application'),
    path('approve_application/<aid>', views.approve_application, name='approve_application'),
    path('suspend_interview/<iid>', views.suspend_interview, name='suspend_interview'),
    path('approve_interview/<iid>', views.approve_interview, name='approve_interview'),
    path('delete_answers/<iid>/<uid>', views.delete_answers, name='delete_answers'),
    path('suspend_user/<uid>', views.suspend_user, name='suspend_user'),
    path('approve_user/<uid>', views.approve_user, name='approve_user'),
    path('employment_update/<uid>', views.employment_update, name='employment_update'),
    path('payroll/update/<pid>', views.update_payroll, name='update_payroll'),
    path('add_note/<uid>', views.add_note, name='add_note'),
    path('delete_note/<account>/<nid>/<uid>', views.delete_note, name='delete_note'),
    path('payroll_histories', views.payroll_histories, name='payroll_histories'),

]
